sudo: required
language: generic
services:
  - docker

befor_install: -docker build -t gshahafridi/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true gshahafridi/docker-react npm run test
